manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/refil
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: refil
      revision: adv360-z3.5-2
      import: app/west.yml

    # ZMK modules
    - name: zmk-adaptive-key
      remove: urob
      revision: v0.2
      path: modules/zmk/adaptive-key
    - name: zmk-auto-layer
      remove: urob
      revision: v0.2
      path: modules/zmk/auto-layer
    - name: zmk-helpers
      remove: urob
      revision: v0.2
      path: modules/zmk/helpers
    - name: zmk-leader-key
      remove: urob
      revision: v0.2
      path: modules/zmk/leader-key
    - name: zmk-tri-state
      remove: urob
      revision: v0.2
      path: modules/zmk/tri-state
  self:
    path: config
